# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
